### PR TITLE
NVM install

### PR DESCRIPTION
**Pull request by ab77**
Change-type: patch

### CODE REVIEW

**Comment by joshbwlng** [comment]
@ab77 I forget, why do we need this again? I guess at some point we plan on removing `nvm` and just use the version of node provided by `open-balena-base`. I'd rather not override the base image if possible.

**Comment by ab77** [comment]
> @ab77 I forget, why do we need this again? I guess at some point we plan on removing `nvm` and just use the version of node provided by `open-balena-base`. I'd rather not override the base image if possible.

you really want to be tied to the version of node in the base image?

**Comment by joshbwlng** [comment]
> you really want to be tied to the version of node in the base image?

@ab77 I'd rather not go off in a custom direction unless necessary.

**Comment by ab77** [comment]
> > you really want to be tied to the version of node in the base image?
> 
> @ab77 I'd rather not go off in a custom direction unless necessary.

You already have `.nvmrc` file in the repo. This allows you to control node version using only one file and not rely of what is installed by default.

**Comment by joshbwlng** [comment]
> You already have `.nvmrc` file in the repo. This allows you to control node version using only one file and not rely of what is installed by default.

@ab77 `.nvmrc` was added in to help developers set up a version of node on their local system that's in line with what's used in the images, not the other way around. As a side note, I've recently stopped using `nvm` as it doesn't switch `npm` to track node.  Ended up with node v16 + npm v6 although nvm was set to track latest lts...

**Pull request closed without merging**
